FROM elixir:alpine
RUN apk add --no-cache git nodejs nodejs-npm build-base

WORKDIR /root/wassup
COPY . /root/wassup

ENV MIX_ENV prod
#ENV APP_URL $APP_URL
ENV APP_HOSTNAME $APP_HOSTNAME
#ENV MAIL_SENDER_EMAIL $MAIL_SENDER_EMAIL
ENV SECRET_KEY_BASE $SECRET_KEY_BASE
ENV DATABASE_URL $DATABASE_URL
#ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID
#ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET
#ENV GOOGLE_REDIRECT_URI $GOOGLE_REDIRECT_URI
#ENV REGISTRATION_DISABLED $REGISTRATION_DISABLED
#ENV SMTP_PROVIDER_DOMAIN $SMTP_PROVIDER_DOMAIN
#ENV SMTP_USERNAME $SMTP_USERNAME
#ENV SMTP_PASSWORD $SMTP_PASSWORD
#ENV SSL_KEY_PATH $SSL_KEY_PATH
#ENV SSL_CERT_PATH $SSL_CERT_PATH

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get --only prod

RUN npm install --prefix ./assets
RUN npm run deploy --prefix ./assets
RUN mix phx.digest

ENV MIX_ENV prod

RUN mix compile

EXPOSE 4000/tcp
EXPOSE 443/tcp

ENTRYPOINT docker/start.sh
